name: Stage the app

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Check if the "stage" label is added
      - name: Stage if labeled
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'stage')
        run: echo "The 'stage' label was added. Staging the app now."
